version: "3"

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3200:3200"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "4200:80"

  db:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "db_data:/data/db"

volumes:
  db_data:
  image_data:
